#version: "2"
services:
  app:
    container_name: e-diocese-backend_app
    restart: always
    build: .
    command: npm run dev
    env_file:
    - .env
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
    dns:
      - 8.8.8.8
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - mongodata:/data/db
    command: ["mongod", "--bind_ip", "0.0.0.0", "--auth"]  
volumes:
  mongodata:
    driver: local